server:
  servlet:
    context-path: /
  port: 8080
spring:
  jackson:
   default-property-inclusion: non_null
  application:
    name: PManager
  datasource:
    #url: jdbc:h2:mem:test
    #driverClassName: org.h2.Driver
    #username: sa
    #password

    url: jdbc:mysql://localhost:3306/pmanagerdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    #h2:
      #console:
       #enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb: localhost
    port: 27017
    database: pmanagerdb
app:
  general:
    pageSize: 3
  security:
    apiKey: thekey
    expirationDays: 2

